import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import Groq from 'groq-sdk'
import { SYSTEM_PROMPTS } from '@/lib/ai/prompts'
import { getRepoTree, getRepoFileContent, createAutoFixPR } from '@/lib/github'
import { sendNexusNotification } from '@/lib/notifications'

const getGroqClient = () => new Groq({ apiKey: process.env.GROQ_API_KEY || 'dummy_for_build' })

export async function POST(request: Request) {
    try {
        const supabase = await createClient()
        const { data: { session } } = await supabase.auth.getSession()

        if (!session || !session.provider_token) {
            return NextResponse.json({ error: 'GitHub Provider Token missing' }, { status: 401 })
        }

        const body = await request.json()
        const { repoFullName, defaultBranch, issueTitle, issueDescription } = body

        if (!repoFullName || !defaultBranch || !issueTitle) {
            return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 })
        }

        // 1. Fetch Repository Context (Lightweight)
        const tree = await getRepoTree(session.provider_token, repoFullName, defaultBranch)
        const packageJson = await getRepoFileContent(session.provider_token, repoFullName, 'package.json')

        const filePaths = tree.tree.filter(i => i.type === 'blob').map(i => i.path).filter(p => !p.includes('node_modules') && !p.includes('.git/'))

        const workspaceContext = `
# Repository Files Tree:
${filePaths.join('\n')}

# package.json:
${packageJson || 'Not found'}
`
        const groq = getGroqClient()

        // 2. Run Groq Auto-Fix Inference
        const completion = await groq.chat.completions.create({
            messages: [
                { role: 'system', content: SYSTEM_PROMPTS.autoFixAgent },
                { role: 'user', content: `WORKSPACE CONTEXT:\n${workspaceContext}\n\nISSUE TO FIX:\nTitle: ${issueTitle}\nDescription: ${issueDescription}\n\nPlease generate the exact file path and complete file content to resolve this issue.` }
            ],
            model: 'llama-3.1-8b-instant',
            response_format: { type: 'json_object' },
            temperature: 0.1, // Very low temp for exact code generation
            max_tokens: 6000,
        })

        const content = completion.choices[0]?.message?.content
        if (!content) throw new Error("No content generated by Groq")

        const fixData = JSON.parse(content)

        if (!fixData.files || !Array.isArray(fixData.files) || fixData.files.length === 0) {
            throw new Error("Invalid fix format generated by AI: 'files' array is missing or empty")
        }

        // 3. Create Pull Request via GitHub API
        const prUrl = await createAutoFixPR(
            session.provider_token,
            repoFullName,
            defaultBranch,
            fixData.files,
            fixData.prTitle || `fix: Auto-Fix for ${issueTitle}`,
            fixData.prBody || `Automated multi-file fix generated by Nexus Intelligence Core.\n\nIssue: ${issueDescription}`
        )

        // Log event
        const { data: { user } } = await supabase.auth.getUser()
        if (user) {
            await supabase.from('events').insert({
                user_id: user.id,
                type: 'autofix_pr',
                title: `Auto-Fix PR Multi-Fichiers : ${fixData.prTitle || issueTitle}`,
                description: `Correction complexe générée pour le dépôt ${repoFullName}. ${fixData.files.length} fichiers modifiés.`,
                metadata: { prUrl, repoFullName, fileCount: fixData.files.length }
            })
        }

        // Send notifications
        const { data: { user: currentUser } } = await supabase.auth.getUser()
        if (currentUser) {
            const { data: settings } = await supabase.from('nexus_settings').select('discord_webhook_url, slack_webhook_url').eq('user_id', currentUser.id).single()
            if (settings) {
                const hook = settings.discord_webhook_url || settings.slack_webhook_url
                if (hook) {
                    await sendNexusNotification(hook, {
                        title: `Auto-Fix PR Déployée : ${fixData.prTitle || issueTitle}`,
                        description: `Dépôt: ${repoFullName}\nFichiers modifiés: ${fixData.files.length}\nPR URL: ${prUrl}`,
                        url: prUrl,
                        type: 'success'
                    })
                }
            }
        }

        return NextResponse.json({ success: true, prUrl, fileCount: fixData.files.length })

    } catch (error) {
        console.error('Auto-Fix Generation Error:', error)
        return NextResponse.json({ error: error instanceof Error ? error.message : 'Unknown error' }, { status: 500 })
    }
}
